# Site settings
author: Joe Hefley
title: It's Hef
header-img: img/home-bg.png
email: joehef34@gmail.com
copyright_name: Joe Hefley
description: > # this means to ignore newlines until "baseurl:"
  Ya Know What They Say
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  itshef

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
